### ISSUE TITLE
No License file present in sources

### ISSUE THREAD

**Issue by pemensik** [zonyitoo/tokio-tfo#8]
I have tried rust2rpm tokio-tfo command to prepare an rpm package of this project.

But it failed with following error:
ERROR: No license files were detected. In almost all cases, this is an issue
       with the upstream project that should be reported.

And indeed. There is no actual MIT license file. Nor is it in comments in source files at least. That prevents packaging this project in linux distributions caring about legality. Can actual license text (from https://spdx.org/licenses/MIT.html for example) be added to the repository, please?

**Comment by zonyitoo** [comment]
Done.

**Comment by pemensik** [comment]
Great, thank you! Would it be possible to have release containing new license text made?

**Comment by zonyitoo** [comment]
Published v0.3.0
